apiVersion: v1
kind: Service
metadata:
  name: memory-fragment-test
spec:
  selector:
    app: memory-fragment-test
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP # Or NodePort, LoadBalancer, ExternalName